### ISSUE TITLE
Chat History Request

### ISSUE THREAD

**Issue by PrimeArchive** [Ruu3f/freeGPT#5]
Hey developer thanks for creating such a great repo for us but I have a question is it possible to send a request along with chat history (in gpt4 and alpaca_7b )? if yes then how?

**Comment by Ruu3f** [comment]
When multiple people chat together, it can be challenging for the model to respond to each person without giving the answer to the other person. However, its possible using a Discord bot since you can create separate threads for each person so the model won't be confused and we can add chat history.
