### ISSUE TITLE
not actually gpt-4

### ISSUE THREAD

**Issue by cabfile** [Ruu3f/freeGPT#6]
part of the supposed gpt-4's response was `"model":"gpt-3.5-turbo-0301"`
can you find another backend?

**Comment by cabfile** [comment]
oh and you.com apparently uses claude, not gpt-3.5

**Comment by Ruu3f** [comment]
> oh and you.com apparently uses claude, not gpt-3.5
you.com actually uses C-A-L, a large language model based on GPT made by you.com themselves. So it isn't using Claude either GPT.

I will make gpt3 to c-a-l (since the package was using you.com for gpt3) and find another provider for gpt3

> part of the supposed gpt-4's response was `"model":"gpt-3.5-turbo-0301"` can you find another backend?

Yeah, about that i will change that soon once i find another one.
